apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: masu-server
  name: masu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: masu-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: masu-server
    spec:
      containers:
        - command:
            - /koku/run_server.sh
          env:
            - name: ACCOUNT_ENHANCED_METRICS
              value: "False"
            - name: API_PATH_PREFIX
              value: /api/cost-management
            - name: AWS_SHARED_CREDENTIALS_FILE
            - name: DATABASE_ENGINE
              value: postgresql
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_SERVICE_NAME
              value: POSTGRES_SQL
            - name: DATABASE_USER
              value: postgres
            - name: DEVELOPMENT
              value: "True"
            - name: DJANGO_READ_DOT_ENV_FILE
              value: "True"
            - name: ENHANCED_ORG_ADMIN
              value: "True"
            - name: GOOGLE_APPLICATION_CREDENTIALS
            - name: GUNICORN_THREADS
              value: "False"
            - name: GUNICORN_WORKERS
              value: "3"
            - name: MASU
              value: "True"
            - name: NOTIFICATION_CHECK_TIME
              value: "24"
            - name: OCI_CLI_KEY_FILE
            - name: OCI_PYTHON_SDK_NO_SERVICE_IMPORTS
              value: "True"
            - name: OCI_SHARED_CREDENTIALS_FILE
            - name: POD_CPU_LIMIT
              value: "1"
            - name: POSTGRES_SQL_SERVICE_HOST
              value: db
            - name: POSTGRES_SQL_SERVICE_PORT
              value: "5432"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /tmp
            - name: RBAC_SERVICE_HOST
              value: rbac-server
            - name: RBAC_SERVICE_PATH
              value: /r/insights/platform/rbac/v1/access/
            - name: RBAC_SERVICE_PORT
              value: "9000"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: RETAIN_NUM_MONTHS
              value: "4"
            - name: RUN_GUNICORN
            - name: S3_BUCKET_NAME
              value: koku-bucket
            - name: S3_BUCKET_NAME_OCP_INGRESS
              value: ocp-ingress
            - name: S3_ENDPOINT
              value: http://koku-minio:9000
            - name: SCHEMA_SUFFIX
            - name: SOURCES_API_PREFIX
              value: /api/sources/v1.0
            - name: SOURCES_API_SVC_HOST
              value: sources
            - name: SOURCES_API_SVC_PORT
              value: "3000"
            - name: SOURCES_PSK
              value: thisMustBeEphemeralOrMinikube
            - name: TAG_ENABLED_LIMIT
              value: "200"
            - name: TRINO_HOST
              value: trino
            - name: TRINO_PORT
              value: "8080"
            - name: TRINO_S3A_OR_S3
              value: s3a
            - name: UNLEASH_HOST
              value: unleash
            - name: UNLEASH_LOG_LEVEL
              value: WARNING
            - name: UNLEASH_PORT
              value: "4242"
            - name: UNLEASH_PREFIX
              value: http
            - name: UNLEASH_TOKEN
          image: koku_base
          name: masu-server
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /koku/.unleash
              name: masu-server-cm1
            - mountPath: /koku/db_functions
              name: masu-server-cm2
            - mountPath: /koku/scripts
              name: masu-server-cm3
            - mountPath: /koku/run_server.sh
              name: masu-server-cm4
              subPath: run_server.sh
            - mountPath: /etc/credentials
              name: masu-server-cm5
          workingDir: /koku
      restartPolicy: Always
      volumes:
        - configMap:
            name: masu-server-cm1
          name: masu-server-cm1
        - configMap:
            name: masu-server-cm2
          name: masu-server-cm2
        - configMap:
            name: masu-server-cm3
          name: masu-server-cm3
        - configMap:
            items:
              - key: run_server.sh
                path: run_server.sh
            name: masu-server-cm4
          name: masu-server-cm4
        - configMap:
            name: masu-server-cm5
          name: masu-server-cm5
