apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:5.0.4
          name: koku-redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
