apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: trino
  name: trino
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    io.kompose.service: trino
