apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trino
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: trino
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: kokuminioaccess
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: kokuminiosecret
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_USER
              value: postgres
            - name: LOCAL
              value: "TRUE"
            - name: MINIO_ENDPOINT
              value: http://koku-minio:9000
            - name: MY_NODE_ID
              value: localhost
            - name: POSTGRES_SQL_SERVICE_HOST
              value: db
            - name: POSTGRES_SQL_SERVICE_PORT
              value: "5432"
            - name: S3_ACCESS_KEY
              value: kokuminioaccess
            - name: S3_BUCKET_NAME
              value: koku-bucket
            - name: S3_SECRET
              value: kokuminiosecret
            - name: TRINO_LOG_LEVEL
              value: INFO
            - name: TRINO_S3A_OR_S3
              value: s3a
          image: quay.io/redhat-services-prod/cost-mgmt-dev-tenant/ubi-trino:470-009
          name: trino
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 10000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/trino/config.properties
              name: trino-cm0
              subPath: config.properties
            - mountPath: /etc/trino/jvm.config
              name: trino-cm1
              subPath: jvm.config
            - mountPath: /etc/trino/log.properties
              name: trino-cm2
              subPath: log.properties
            - mountPath: /etc/trino/catalog/hive.properties
              name: trino-cm3
              subPath: hive.properties
            - mountPath: /etc/trino/catalog/glue.properties
              name: trino-cm4
              subPath: glue.properties
            - mountPath: /etc/trino/catalog/postgres.properties
              name: trino-cm5
              subPath: postgres.properties
            - mountPath: /data/trino/data
              name: trino-cm6
            - mountPath: /data/trino/logs
              name: trino-cm7
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.properties
                path: config.properties
            name: trino-cm0
          name: trino-cm0
        - configMap:
            items:
              - key: jvm.config
                path: jvm.config
            name: trino-cm1
          name: trino-cm1
        - configMap:
            items:
              - key: log.properties
                path: log.properties
            name: trino-cm2
          name: trino-cm2
        - configMap:
            items:
              - key: hive.properties
                path: hive.properties
            name: trino-cm3
          name: trino-cm3
        - configMap:
            items:
              - key: glue.properties
                path: glue.properties
            name: trino-cm4
          name: trino-cm4
        - configMap:
            items:
              - key: postgres.properties
                path: postgres.properties
            name: trino-cm5
          name: trino-cm5
        - configMap:
            name: trino-cm6
          name: trino-cm6
        - configMap:
            name: trino-cm7
          name: trino-cm7
