apiVersion: v1
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://trino:8080

    jmx.rmiserver.port=10000
    jmx.rmiregistry.port=10000
    query.max-length=10000000

    web-ui.authentication.type=fixed
    web-ui.user=trino
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: trino
  name: trino-cm0
